kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: linode-block-storage
  namespace: kube-system
provisioner: linodebs.csi.linode.com
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: linode-block-storage-expand
  namespace: kube-system
provisioner: linodebs.csi.linode.com
reclaimPolicy: Delete
allowVolumeExpansion: true
