apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linode-csi-role
  namespace: {{ required ".Values.namespace required" .Values.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
