apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
namespace: kube-system
patchesStrategicMerge:
  - |-
    kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: csi-resizer-role-cfg
    $patch: delete
  - |-
    kind: Role
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: external-resizer-cfg
    $patch: delete
  - |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: csi-resizer
    $patch: delete
patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: external-resizer-runner
    patch: |-
      - op: replace
        path: /metadata/name
        value: external-resizer-role
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: csi-resizer-role
    patch: |-
      - op: replace
        path: /metadata/name
        value: csi-controller-resizer-binding
      - op: replace
        path: /subjects/0/name
        value: csi-controller-sa
      - op: replace
        path: /subjects/0/namespace
        value: kube-system
   
