name: Release manifests
on:
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # pin@master
      - name: Build manifest
        run: "./hack/release-yaml.sh ${{ github.event.release.tag_name }}"
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -- pkg/linode-bs/deploy/releases/linode-blockstorage-csi-driver*\.yaml
          git commit -m "Update manifests"
      - name: Push changes
        uses: ad-m/github-push-action@65392840bda2e774394d5cd38ca33e5918aec2d3 # pin@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
